# Generated by Django 3.1.4 on 2021-01-13 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='data_ingresso',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nascimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
