# Generated by Django 3.1.4 on 2021-03-31 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Aluguel', '0003_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='apartamento',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='imovel',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='pessoa',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='valor_agua',
            field=models.CharField(default=2000, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='valor_aluguel',
            field=models.CharField(default=33000, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='valor_multa',
            field=models.CharField(default=200, max_length=10),
            preserve_default=False,
        ),
    ]
