# Generated by Django 3.1.4 on 2021-04-06 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aluguel', '0005_auto_20210406_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='imovel_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aluguel.imovel'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='pessoa_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aluguel.pessoa'),
        ),
    ]
